
plugins {
  id 'java'
  id 'maven-publish'
  id 'io.freefair.lombok' version '8.6'
}

dependencies {
  implementation libraries.base
  implementation libraries.apacheBase
  annotationProcessor libraries.autoService
  implementation project(':luwrain-base')
  annotationProcessor project(':luwrain-base')
  implementation project(':luwrain')
  implementation project(':luwrain-bookdoc')
  implementation 'org.apache.pdfbox:pdfbox:2.0.29'
  implementation 'javax.activation:activation:1.1.1'
  testImplementation libraries.junit
}

tasks.named('test') {
    useJUnitPlatform()
}

publishing {
  publications {
    mavenJava(MavenPublication) {
      groupId = 'org.luwrain'
      artifactId = 'luwrain-reader'
      version = ver.lwr
      from components.java
    }
  }
  repositories {
    maven {
      url = uri(mavenDestRepo)
    }
  }
}
